neo4j/cypher-language-support

README.md, imgs/repo-overview.png, packages/react-codemirror-playground/vite.config.ts
The demo is no longer served on the root of it's domain, so we need to update the vite config for the demo build as per [vite docs on github pages](https://vitejs.dev/guide/static-deploy.html#github-pages).
=> fix pages demo & add missing image

.gitattributes
Ignores `semanticAnalysis.js` file from GH stats.
To get the stats about the languages used in the repo better:
=> Tries to ignore .js file from GH language stats

packages/language-support/src/highlighting/syntaxValidation/syntaxValidation.ts, packages/language-support/src/tests/highlighting/syntaxValidation/semanticValidation.test.ts
Because the offset wasn't correctly placed:
=> Fixes semantic errors positions in codemirror

packages/language-support/README.md
`validateSyntax` crashes if you don't provide the schema prop
=> fix example

packages/language-server/README.md
After the nvim-lspconfig project has now merged the support for the `cypher-language-server` (https://github.com/neovim/nvim-lspconfig/commit/cedc13473c7ff65bfc85cf3a9cfa65f7876a03b8), it might be a good idea to add also the information here.
=> Add information about neovim support.

.changeset/pre.json, .changeset/quick-berries-report.md, package-lock.json, packages/react-codemirror-playground/CHANGELOG.md, packages/react-codemirror-playground/package.json, packages/react-codemirror-playground/src/App.tsx, packages/react-codemirror/CHANGELOG.md, packages/react-codemirror/package.json, packages/react-codemirror/src/CypherEditor.tsx, packages/react-codemirror/src/e2e_tests/history-navigation.spec.tsx, packages/react-codemirror/src/e2e_tests/syntax-validation.spec.tsx, packages/react-codemirror/src/history-navigation.ts
We need more control of what is in the editor history in query, so I've moved it to be externally controlled. If we see the need for uncontrolled history, we can add an `uncontrolledHistory` prop to make `onExecute` push to history again.
=> Make editor history controlled and `onExecute` reactive

.changeset/stale-donkeys-grow.md, packages/language-support/src/autocompletion/completionCoreCompletions.ts, packages/language-support/src/tests/autocompletion/databasename-completion.test.ts, packages/language-support/src/tests/autocompletion/misc-completions.test.ts, packages/language-support/src/tests/autocompletion/variable-completion.test.ts
We have logic for knowing when to complete the next vs current word. Our logic only moved the cursor back for identifier, so it didn't work when there was overlap between identfiers and keywords. For example:
`SHOW DAT` correctly suggests `DATABASE`
but
`SHOW DATA` would not.
=> Fix incorrect completions when identifier overlaps with keyword

.changeset/purple-buckets-applaud.md, packages/react-codemirror/src/CypherEditor.tsx
The shortcut of comparing lengths works fine until you hit the maximum history length in workspace -> every new entry pushes an old one out, meaning the length of history entries is constant. I now also compare the newest history entry
=> improve history prop change detection

packages/vscode-extension/src/extension.ts
The `neo4j.trace.server` setting wasn't working to debug the messages in the language server when set to other value rather than `verbose`. 
That's cause it's provided by VSCode for language servers and lives under the namespace we pass when setting up the client. We were passing `cypherLSP` still.
=> Solves a problem with the trace.server

packages/language-support/src/signatureHelp.ts, packages/language-support/src/tests/signatureHelp.test.ts
Fixes the case of getting the overlay with the information about the first argument for functions.
`RETURN apoc.do.when(` gets parsed as:
```
statements
/    |    \     
statement (    EOF
/  \
RETURN  expression
```
rather than:
```
statements
/    |    \     
statement (    EOF
/  \
RETURN  functionInvocation
```
so we need to treat that case differently because we cannot modify the relative priority of functionInvocation vs expression
`RETURN apoc.do.when(x` gets parsed correctly in contrast (when we've started the first argument), because the parser has enough information to recognize it is a function invocation.
When our final character is `(`, just go to the preceeding statement and traverse it to find whether it ends on a expression. If it does, that's our function name.
=> Fixes signature help edge case

package-lock.json
To keep the packages clean of security vulnerabilities:
```
browserify-sign  2.6.0 - 4.2.1
Severity: high
browserify-sign upper bound check issue in `dsaVerify` leads to a signature forgery attack - https://github.com/advisories/GHSA-x9w5-v3q2-3rhw
fix available via `npm audit fix`
node_modules/browserify-sign
vite  4.5.0
Severity: moderate
Vite XSS vulnerability in `server.transformIndexHtml` via URL payload - https://github.com/advisories/GHSA-92r3-m2mg-pj97
fix available via `npm audit fix`
node_modules/@playwright/experimental-ct-core/node_modules/vite
node_modules/@playwright/experimental-ct-react/node_modules/vite
packages/react-codemirror-playground/node_modules/vite
packages/react-codemirror/node_modules/vite
2 vulnerabilities (1 moderate, 1 high)
```
=> Updates dependency versions

.github/workflows/benchmark.yaml
The first grafana job published metrics properly, the e2e benchmark failed since playwright didn't have it's browser installed
=> fix second half of grafan push

packages/language-server/src/linting.ts, packages/vscode-extension/e2e_tests/fixtures/syntax-validation.cypher, packages/vscode-extension/e2e_tests/tests/syntax-validation.spec.ts
When writing something with an error, i.e `MATCH (n)` in VSCode, and replacing it with an empty query, we were still showing the old error.
Because we were not sending empty diagnostics in the case of an empty query.
=> Corrects a bug with an empty query in VSCode

packages/language-server/src/server.ts
We have no support for parameters in VS Code yet so the `$` will not really do anything for now, but we might as well add it in for when we do
=> update trigger characters to match codemirrors

CONTRIBUTING.md, README.md, package-lock.json, packages/language-server/package.json, packages/language-server/src/server.ts, packages/language-server/src/types.ts, packages/language-support/src/signatureHelp.ts, packages/language-support/src/tests/signatureHelp.test.ts, packages/vscode-extension/.vscodeignore, packages/vscode-extension/README.md, packages/vscode-extension/e2e_tests/fixtures/.vscode/settings-template.json, packages/vscode-extension/images/demo.gif, packages/vscode-extension/images/logo.png, packages/vscode-extension/package.json
Fixes the crash when dbschema isn't passed to the signature help and prepares our package for publishing.
Updates to our package.json based on the guidelines in the docs here:
https://code.visualstudio.com/api/references/extension-manifest
I've updated some "VSCode" to "VS Code", since that's how it's usually written in docs from microsoft.
Minimized the extension bundle, now it only includes the relevant files:
The gif needs to be referenced via https to render in the marketplace, as noted [here](https://stackoverflow.com/questions/52686381/why-image-cant-show-up-in-the-vs-code-extension-gallery-when-i-used-html-tag-in) and [here](https://stackoverflow.com/questions/42988322/insert-video-in-readme-md-for-an-extension-of-vscode). Let me know if you prefer one of the older gifs, a static …
=> Prepare for extension publishing

.changeset/config.json, .changeset/pre.json, package-lock.json, packages/vscode-extension/CHANGELOG.md
Excludes the VScode from changesets.
Because we have a situation where all of the other packages are in a pre-release mode, but `changesets` looks like it's unable to handle some of the packages being in a pre-release mode and some not (VSCode Marketplace will not admit the `1.0.0-next` naming convention).
Therefore it's better to write the changelogs for VSCode by hand until we get out of pre-release mode.
=> Ignores VSCode in changeset until we make a first non-next release

packages/language-support/src/autocompletion/completionCoreCompletions.ts, packages/language-support/src/tests/autocompletion/miscCompletions.test.ts
When completing something that could have a symbolic name completion but there are none, there was a code path that returned undefined (surprised ts didn't catch this, we should harden the config). 
repro steps in image:
=> fix bug where symbolicname completions could return invalid completions

turbo.json
Because the `dist` output for the language-server is still missing if we clean and rebuild. If we override a `#build` project inside turbo, we need to also add the `outputs`
=> Fixes outputs missing in turbo with the language-server

.github/workflows/ci.yaml, jest.config.base.js, packages/language-support/tsconfig.json, tsconfig.base.json
This makes `tsc` not care about the `semanticAnalysis.js` file when emitting type declarations, but it's still bundling it with `esbuild`
Before:
After:
Also the semantic analysis tests run really fast now and the debugger works way way faster when setting up a debug point in the code.
=> Speeds up build and tests

.changeset/chilled-dots-guess.md, packages/react-codemirror/src/lang-cypher/createCypherTheme.ts, packages/react-codemirror/src/lang-cypher/signatureHelp.ts
This change let's the signature help appear below the editor if there's not enough space to render it above. I'm not 100% certain why, when the tooltip rendered below it started overflowing again unless I set the max height directly.
=> support signature help below as well

.changeset/gentle-pans-rescue.md, packages/language-support/src/signatureHelp.ts, packages/language-support/src/tests/signatureHelp.test.ts
Fixes bug with showing wrong signature help of a function nested inside a procedure `CALL`.
We were setting the signature help on exiting contexts. That means if we had a `CALL procedure(function(` we were exiting the procedure context last, setting the signature help to the procedure where the caret is contained.
Instead it suffices with the setting the signature help when entering a context.
=> Fixes bug with signature help of functions nested inside procedures

.github/workflows/publish-vscode-extension.yaml
Because there was a minor bug in that file:
=> Fixes bug in yaml files for the VSCode publish job

.changeset/curvy-singers-greet.md, packages/react-codemirror-playground/src/App.tsx, packages/react-codemirror/src/CypherEditor.tsx, packages/react-codemirror/src/e2e_tests/configuration.spec.tsx
Adding an 'ariaLabel' prop to the CyperEditor props so that we can set an aria-label attribute on the codemirror editor.
This uses the [contentAttributes](https://codemirror.net/docs/ref/#view.EditorView^contentAttributes) facet, which may be extended later to add more DOM attributes, or changed to accept a kvp/Record so that DOM attributes may be fully flexible.
with the `ariaLabel` property set, we can see the attribute set in the playground:
The property is optional, so not setting it should result in the aria-label attribute not being added to the editor:
=> Add an ariaLabel prop to CypherEditor

release-canary.js
Builds only `language-support` and `react-codemirror` when releasing canary packages.
Because when we merged #216 the process to release to canary started to fail. That is because a new prop was added to `react-codemirror`, and the script does not update the package.json of `react-codemirror-playground` package that depends on it, so it was failing on build.
Building only the packages we intend to publish to npm as canary releases solves the issue.
=> Fixes bug with canary release script

.github/workflows/publish-vscode-extension.yaml, packages/vscode-extension/CHANGELOG.md, packages/vscode-extension/package.json
I've published the new version v1.2.1 manually so that the icon doesn't stay broken for the weekend.
Checks out the repo with git lfs in the release job. Because the logo of the extension wasn't being packaged correctly:
We were failing in the publish job with:
```
Run npx ovsx publish -p $VSX_PAT
npx ovsx publish -p $VSX_PAT
shell: /usr/bin/bash -e {0}
env:
NODE_OPTIONS: --max_old_space_size=[4](https://github.com/neo4j/cypher-language-support/actions/runs/9598143476/job/26468739762#step:8:4)096
VSX_PAT: ***
❌  Missing required field 'publisher'.
See the documentation for more information:
https://github.com/eclipse/openvsx/wiki/Publishing-Extensions
Error: Process completed with exit code 1.
```
Unfortunately OVSX seems to be [flakey](https://github.com/eclipse/openvsx/issues/945) at …
=> Adjusts VSCode extension GitHub Actions job

packages/react-codemirror/src/e2e_tests/historyNavigation.spec.tsx, packages/react-codemirror/src/historyNavigation.ts
Puts the cursor at the start of the query when navigating backwards, so that you can just press up once more to move further back in the history.
https://github.com/neo4j/cypher-language-support/assets/10564538/1c36ec52-4f55-48cb-b076-df76c9c4441e
=> faster history movement

.eslintignore, .vscode/launch.json, package-lock.json, package.json, packages/vscode-extension/e2e_tests/helpers.ts, packages/vscode-extension/e2e_tests/main.ts, packages/vscode-extension/e2e_tests/setupTestContainer.ts, packages/vscode-extension/e2e_tests/suiteSetup.ts, packages/vscode-extension/e2e_tests/testRunnerDebug.ts, packages/vscode-extension/e2e_tests/tests/executeCommands.spec.ts, packages/vscode-extension/e2e_tests/tests/syntaxValidation.spec.ts, packages/vscode-extension/esbuild.js, packages/vscode-extension/package.json, turbo.json
This PR improves the debug-ability of the vscode extension, both the e2e/unit tests and the extension itself.
I have extracted these changes out of the side panel PR.
- I am introducing an `esbuild.js` config file that only minifies if we pass a `--production` flag to it, and will otherwise produce a sourcemap for the extension
- I am adding some `dev` namespaced tasks in the extension package that will produce non-minified js and sourcemaps for the extension, which, both the vs code launch tasks will use
- I am adding a new launch task for debugging the extension tests
- I am modifying a few tests that use the `process.env` variables so that they don't fall over when debugging tests, though these are still dependent on you having an instance running locally
=> Improve debug-ability of vscode extension

.changeset/eleven-scissors-type.md, packages/react-codemirror-playground/src/App.tsx, packages/react-codemirror/src/CypherEditor.tsx
This PR fixes the issue outlined below.
> A side effect of typing and executing a query quickly is that it stick around in the editor, see video:
> https://github.com/user-attachments/assets/431bec1a-21ce-479c-a71e-9855e175af81
> 
> I think this might have been a problem before, but I feel it might be more noticeable with these changes. It looks like the debounced `onChange` event fires after the `execute` callback fires it's  `setCodemirrorVal('');`. 
> 
> I think the proper way to get around it is to cancel the debounced update if the `value` prop is externally set. I think this would do the trick: 
> ![CleanShot 2024-07-15 at 14 19 23@2x](https://github.com/user-attachments/assets/0f717aac-d438-4342-a952-5bbc9bdb6a76)
_Originally posted by @OskarDamkjaer in …
=> Fix bug causing debounced value to override value

.changeset/strong-squids-relax.md, packages/react-codemirror/src/CypherEditor.tsx
Fix a bug causing debounced value updates to get cancelled erroneously
=> Update logic for handling externally set values

packages/schema-poller/src/index.ts, packages/schema-poller/src/neo4jConnection.ts, packages/vscode-extension/e2e_tests/helpers.ts, packages/vscode-extension/e2e_tests/mocks/mockSchemaPoller.ts, packages/vscode-extension/e2e_tests/suiteSetup.ts, packages/vscode-extension/e2e_tests/tests/connectionService.spec.ts, packages/vscode-extension/e2e_tests/tests/connectionTreeDataProvider.spec.ts, packages/vscode-extension/e2e_tests/tests/syntaxValidation.spec.ts, packages/vscode-extension/src/connectionService.ts, packages/vscode-extension/src/connectionTreeDataProvider.ts, packages/vscode-extension/src/connectionTreeDecorationProvider.ts, packages/vscode-extension/src/contextService.ts, packages/vscode-extension/src/registrationService.ts, packages/vscode-extension/src/webviews/controllers/connectionPanelController.ts
This change updates the connection tree view to include a dropdown for active connections that will list the database available for that connection.
The home database is annotated with a 'Home' emoji
The active database is highlighted green, and annotated with an 'active' label
To facilitate this, I am exposing the databases array that's established in the neo4j connection - my thinking is we needn't over complicate this by doing anything too clever, like automatically refreshing the list of databases when the schema poller refetches data since databases are likely to be fairly static
=> Listing databases for an active Connection

packages/schema-poller/src/schemaPoller.ts, packages/vscode-extension/e2e_tests/tests/commandHandlers.spec.ts, packages/vscode-extension/e2e_tests/tests/executeCommands.spec.ts, packages/vscode-extension/package.json, packages/vscode-extension/src/commandHandlers.ts, packages/vscode-extension/src/connectionService.ts, packages/vscode-extension/src/constants.ts, packages/vscode-extension/src/registrationService.ts, packages/vscode-extension/src/uiUtils.ts, packages/vscode-extension/src/webviews/connectionPanel.ts, packages/vscode-extension/src/webviews/controllers/connectionPanelController.ts
This change updates the connection tree view to include a context menu option to databases in the treeview and accompanying command handler to switch databases. It also removes the optional `database` field in the connection form.
=> Adding a 'switch to database' command to databases in the tree view

packages/react-codemirror/src/lang-cypher/syntaxValidation.ts, packages/react-codemirror/src/viteEnv.d.ts
I noticed a minor stylistic issue in how a worker was imported. Fixed by adding the [Vite client types](https://vitejs.dev/guide/features#client-types).
=> Replace ts-ignore with proper Vite types

.changeset/ninety-panthers-pretend.md, package-lock.json, packages/react-codemirror/package.json, packages/react-codemirror/src/CypherEditor.test.tsx, packages/react-codemirror/src/CypherEditor.tsx, packages/react-codemirror/src/constants.ts, packages/react-codemirror/src/e2e_tests/autoCompletion.spec.tsx, packages/react-codemirror/src/e2e_tests/debounce.spec.tsx, packages/react-codemirror/vite.config.ts
This PR once again attempts to fix the issues with how the `CypherEditor` handles state updates. I'll try to explain below what the problem is and how we could solve it.
TL;DR the `CypherEditor` now flushes debounced changes before `onExecute`, and handles `this.prop.value` updates by checking if `this.props.value` is different from `prevProps.value`.
1. Set up a controlled `CypherEditor` component as follows:
```tsx
const [value, setValue] = useState('');
return <CypherEditor value={value} onChange={setValue} onExecute={() => setValue('')} />
```
3. Input `"foo"` and then immediately press Enter. This must be done quickly; the component debounces its `onChange` calls with a 200 ms timer. This means `onChange` is called 200 ms after user stops typing instead of being called on every …
=> Fix CypherEditor state handling and add tests

package-lock.json, package.json, packages/schema-poller/src/index.ts, packages/schema-poller/src/neo4jConnection.ts, packages/vscode-extension/src/webviews/resultWindow.ts
Adds a new cypher running function for user queries instead of the one created for Neo4j SDK functions. It's using the [AsyncIterator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/AsyncIterator) api in the driver to stop consuming records after a set limit is hit. I also update the view to inform the user if the limit was hit.
I got an error message from Turborepo that told me to update the version 🤷
=> Add row limit to query execution

.changeset/young-llamas-teach.md, packages/react-codemirror/src/index.ts
No need to list all the public exports `@neo4j-cypher/language-support` on by one
=> Re-export language support from react codemirror

.changeset/shiny-dodos-rush.md, packages/react-codemirror/src/CypherEditor.tsx, packages/react-codemirror/src/neo4jSetup.tsx
It would be useful to expose this property so that we are able to override the tab behaviour of the editor.
By default in the neo4j setup, we set up handlers for Tab and Shift-Tab - however this traps the user in the editor. Whilst it's then possible to use Esc to remove focus from the editor, in some circumstances (e.g. the editor is in a modal where Esc closes the modal), it'd be nice to be able to disable tab trapping - even though this does mean disabling Tab for accepting autocompletions
https://codemirror.net/docs/ref/#view.EditorView.setTabFocusMode
=> Expose tab focus mode prop so we can override tab-trapping behaviour

packages/language-support/src/signatureHelp.ts, packages/language-support/src/tests/testData.ts, packages/react-codemirror/src/e2e_tests/signatureHelp.spec.tsx, packages/react-codemirror/src/lang-cypher/createCypherTheme.ts, packages/react-codemirror/src/lang-cypher/signatureHelp.ts
Some work has gone into updating descriptions of procedures and functions so it has broken the signature help functionality for newer versions. Our e2e tests were already failing because of that.
In VSCode:
In codemirror:
In VSCode:
In codemirror:
=> Fixes signature help

.changeset/loud-shrimps-push.md, packages/language-server/src/autocompletion.ts, packages/react-codemirror/src/lang-cypher/autocomplete.ts, packages/vscode-extension/CHANGELOG.md, packages/vscode-extension/package.json, packages/vscode-extension/src/commandHandlers.ts, packages/vscode-extension/src/constants.ts, packages/vscode-extension/src/registrationService.ts
* Completions are a bit broken, so I'm going to push a small hotfix that reverts to just reparsing up to the cursor. That would come with a performance hit, but it won't be noticeable unless on a big query. I prefer the demo tomorrow to be neat.
* It would be handy to get a button on the context menu to open the current selection in a temp file selecting the language cypher (instead of the user having to copy paste text, create the file manually, etc)
Ahead of the NODES talk, we want the VSCode extension to work smoothly
=> Adds minor nits to the VSCode extension

.changeset/angry-beers-explain.md, package-lock.json, packages/language-support/src/signatureHelp.ts, packages/vscode-extension/CHANGELOG.md, packages/vscode-extension/package.json
=> Fixes signature help bug with default arguments in VSCode

.changeset/old-shoes-provide.md, packages/language-support/src/autocompletion/completionCoreCompletions.ts, packages/language-support/src/parserWrapper.ts, packages/language-support/src/tests/autocompletion/procedureCompletion.test.ts
When we have a procedure call like:
```
CALL db.labels() YIELD
```
we want to get completions for the different return elements the procedure can produce.
This PR adds that.
=> Adds completion for YIELD elements in a procedure call

package-lock.json, packages/language-support/src/parserWrapper.ts, packages/language-support/src/tests/syntaxValidation/semanticValidation.test.ts
It only extracts the statement in the command parsing, omitting the preparsing options.
We were not showing semantic errors correctly for queries that included a preparsing option, because the semantic analysis does not have a preparser inside, it expects already a pre-processed query.
```
EXPLAIN MATCH (n)
// It should be showing an error in the MATCH (n) here because we are missing a RETURN
```
=> Fixes bug with preparser options making semantic errors not show up correctly

packages/language-support/src/autocompletion/completionCoreCompletions.ts
Updates existing change adding YIELD autocompletions so that we check suggestions against existing elements stored in a Set (Hash-set) so that it's reliably quick in case of large amounts of return names.
=> List -> Set in checking existing yield items 

.changeset/nice-jokes-give.md, packages/language-support/src/autocompletion/completionCoreCompletions.ts, packages/language-support/src/tests/autocompletion/patternCompletion.test.ts, packages/language-support/src/tests/autocompletion/propertykeyCompletion.test.ts
Before if for example had relationship rel_123, we autocompleted `MATCH (n)-[:rel^]` to
` MATCH (n)-[:`\``rel_123`\``] `
Now instead we dont backtick if we have underscore and numbers in label names/rel names/properties and just give
`MATCH (n)-[:rel_123]`
=> Alter so labels with numbers and underscores dont get needless backticks

packages/react-codemirror/src/e2e_tests/debounce.spec.tsx
I've carded this as one of the paper cuts we should address in Q1.
After a serious of PRs trying to address debouncing problems, the functionality seems to still be flaky somehow
https://github.com/neo4j/cypher-language-support/pulls?q=is%3Apr+author%3Adanieladugyan+is%3Aclosed
=> Disables flaky debouncing test

package-lock.json, packages/language-server/src/linting.ts, packages/language-server/src/server.ts, packages/vscode-extension/CHANGELOG.md, packages/vscode-extension/package.json, packages/vscode-extension/tests/fixtures/deprecated-by.cypher, packages/vscode-extension/tests/specs/api/syntaxValidation.spec.ts, packages/vscode-extension/tests/suiteSetup.ts
The failing behaviour can be seen in the test added by 706f9ec.
Because if we ask to lint a document when the schema is yet not fetched, we will never see schema dependent errors (non existent labels, deprecation warnings, non existent procedures, etc). This can happen when we open the  the editor open with a cypher file when we haven't yet connected to a database.
Conversely, when we disconnect from a database, this should also relint the document.
This will become more relevant when we have several connections and we can be connected to different databases with different procedures / functions, different labels, ...
=> Relints documents when connecting / disconnecting to a database

packages/language-support/src/antlr-grammar/CypherCmdParser.g4, packages/language-support/src/parserWrapper.ts, packages/language-support/src/syntaxColouring/syntaxColouring.ts, packages/language-support/src/tests/consoleCommands.test.ts, packages/react-codemirror/src/e2e_tests/e2eUtils.ts, packages/react-codemirror/src/e2e_tests/helpers.spec.tsx, packages/react-codemirror/src/e2e_tests/syntaxValidation.spec.tsx
Cypher5/25Parser.g4 define
parameter[String paramType]
: DOLLAR parameterName[paramType]
;
parameterName[String paramType]
: (symbolicNameString | UNSIGNED_DECIMAL_INTEGER)
;
In CypherCmdParser.g4 instead we had:
paramsCmd: PARAM paramsArgs?;
paramsArgs: (CLEAR | listCompletionRule | map | lambda);
lambda: unescapedSymbolicNameString EQ GT expression;
So params created with lambda could never be escaped, even though regular parser allows it. this aligns cmd-parser with regular.
=> Changes param in cmd-parser to take escaped strings too

.changeset/cuddly-vans-flash.md, packages/language-support/src/syntaxValidation/syntaxValidation.ts, packages/language-support/src/tests/syntaxValidation/functionsValidation.test.ts, packages/language-support/src/tests/syntaxValidation/proceduresValidation.test.ts
Will yield errors like:
`CALL abs(-50) YIELD *` -> Procedure abs is not present in the database. Did you mean to call the function abs? Only procedures can be called inside a CALL clause.
and
`RETURN apoc.create.uuids(50)` -> Function apoc.create.uuids is not present in the database. Did you mean to call the procedure apoc.create.uuids? Procedures must be called inside a CALL clause.
Instead of the regular "Procedure/Function is not present in the database"-messages.
=> Added hint when using function as procedure and vice versa

.changeset/silent-kangaroos-melt.md, packages/language-support/src/helpers.ts, packages/language-support/src/parserWrapper.ts, packages/language-support/src/syntaxValidation/syntaxValidation.ts, packages/language-support/src/tests/syntaxValidation/syntacticValidation.test.ts
We are reporting a missing label for a relationship type when it's a node predicate. This pr fixes that bug.
Because we were traversing the tree to check whether we were inside a node pattern first, without accounting for the fact we could be in a relationship type inside a node predicate.
=> Fixes bug reporting missing label / rel type when inside opposite pattern

.changeset/serious-ducks-sleep.md, packages/language-support/src/antlr-grammar/CypherCmdParser.g4, packages/language-support/src/tests/syntaxColouring/preparser.test.ts
The rule we override to allow the console commands in the parser to be used as variable names, labels, etc was not the correct one, so we couldn't use `clear`, `param`, etc in some places in the query:
```
antlr4-parse ./{CypherCmdLexer.g4,CypherCmdParser.g4} statementsOrCommands
CREATE (n:clear {use: 0})
WITH $param AS map
RETURN map.propertyKey
line 1:10 mismatched input 'clear' expecting {ESCAPED_SYMBOLIC_NAME, ACCESS, ACTIVE, ADMIN, ADMINISTRATOR, ALIAS, ALIASES, ALL_SHORTEST_PATHS, ALL, ALTER, AND, ANY, ARRAY, AS, ASC, ASCENDING, ASSIGN, AT, AUTH, BINDINGS, BOOL, BOOLEAN, BOOSTED, BOTH, BREAK, BUILT, BY, CALL, CASCADE, CASE, CHANGE, CIDR, COLLECT, COMMAND, COMMANDS, COMPOSITE, CONCURRENT, CONSTRAINT, CONSTRAINTS, CONTAINS, COPY, CONTINUE, COUNT, CREATE, CSV, CURRENT, DATA, DATABASE, …
```
=> Fix bug using console commands as variables labels

.changeset/blue-penguins-worry.md, packages/language-support/src/dbSchema.ts, packages/language-support/src/parserWrapper.ts, packages/language-support/src/syntaxValidation/semanticAnalysisWrapper.ts, packages/language-support/src/syntaxValidation/syntaxValidation.ts, packages/language-support/src/tests/syntaxValidation/semanticValidation.test.ts, packages/language-support/src/types.ts, packages/schema-poller/src/metadataPoller.ts, packages/schema-poller/src/queries/databases.ts
Now if defaultLanguage-field is defined on a database, this language version will be used by default in the analysis, otherwise cypher 5 is used.
If the version is defined in-query, like `CYPHER 25 ...` this version will overwrite the default version, if it is given in an array of supported versions we store ourselves (currently 5 and 25).
=> Adds support for cypher versions in semantic analysis-linting

packages/language-support/src/formatting/formatting.ts, packages/language-support/src/formatting/formattingHelpers.ts, packages/language-support/src/tests/formatting/formatting.test.ts
Initial implementation of our cypher formatter. Note that the code does nothing beyond running its own tests at this stage.
The reason I am opening a PR despite it not actually doing anything is that we're already up to several hundred LOC, and reviewing huge PRs is not fun. So this is an attempt at introducing a PR early to avoid too much code in once PR, but still making it big enough to actually introduce meaningful code. It's still huge though, sorry 😅 .
I've been (very) generous with the amounts of comments, and it might be a bit verbose. The reasoning is that methods should have a compelling reason to exist, or they should not exist at all, and instead be handled by the general cases. So to keep track of why something is needed, and to be able to evaluate if it still is after new …
=> Adds baseline formatter implementation

packages/language-support/src/formatting/formatting.ts, packages/language-support/src/formatting/formattingHelpers.ts, packages/language-support/src/formatting/standardizer.ts, packages/language-support/src/tests/formatting/formatting.test.ts
When formatting, we want to ensure that we do not accidentally modify the parse tree in doing so. As a way of implementing this, I propose a "standardizer" which simply walks the tree and prints it as is, in order to make sure we don't e.g. drop some terminal nodes. This PR adds such a standardizer and runs it on every test. The idea is also to use this on a larger sample of queries once we get access to these (I've asked in #product_analytics). 
Since some styleguide rules change the tree, we can't simply do a comparison between the parsetree.toStringTree() strings. One styleguide rule says that ON CREATE should come before ON MATCH for instance, and so we need to take this into account in the standardizer. 
- npm run test
=> Adds standardization check to formatter tests

packages/language-support/src/formatting/formatting.ts, packages/language-support/src/tests/formatting/formatting.test.ts
Adds two things missing from the styleguide recommendations:
1. (bugfix) - no space between dollar sign and parameter name
2. Subquery clauses shuold get indentation like the exists clauses, e.g. this query
```
CALL () { RETURN 'hello' AS innerReturn }
```
should be formatted into
```
CALL () {
RETURN 'hello' AS innerReturn
}
```
I've also added a couple of examples from the styleguide into the tests, such as the "no padding space within function call parentheses" one.
- npm run test 
- unit tests included in this PR for the new features
=> Adds subquery and parameter handling to formatter

packages/language-support/src/formatting/formatting.ts, packages/language-support/src/formatting/formattingHelpers.ts, packages/language-support/src/formatting/standardizer.ts, packages/language-support/src/index.ts, packages/language-support/src/tests/formatting/formatting.test.ts, packages/react-codemirror-playground/src/App.tsx, packages/react-codemirror/src/CypherEditor.tsx
This pull request has the intent to connect the formatter with the Query Editor part of the repo. The Query Editor imports the formatter and then exposes the formatting functionality by a function but also allows the formatter to be ran by key-binding. The package react-codemirror-playground adds a button (see picture) which also runs the formatter. 
The functionality of the formatter is hidden behind a feature flag in react-codemirror-playground/src/App.tsx. Change the constant formatFlag to true in order to test. 
Tested by running `npm run test` in root directory. All tests passed.
=> Add formatting keybind button

packages/react-codemirror-playground/src/App.tsx, packages/react-codemirror/src/CypherEditor.tsx
- Removes hardcoded formatting keybindings from `react-codemirror` package
- Allows clients to configure their own custom formatting keybindings
- Implements formatting keybinding in playground using `extraKeyBindings` parameter
Npm run test works, no tests added
=> moves format keybinding to playground

.github/workflows/deploy-demo.yml, packages/react-codemirror-playground/vite.config.ts
Reverts https://github.com/neo4j/cypher-language-support/pull/315 because GitHub does not seem to be able to properly deploy it to GitHub Pages:
It's better to live with us not being able to use the codemirror playground in Firefox locally than with a globally broken GitHub deploy.
I deployed the branch temporarily to https://neo4j.github.io/cypher-language-support in this commit [35fc692](https://github.com/neo4j/cypher-language-support/pull/337/commits/35fc692cb989f51034997440ba0f61f806c34923) to check that the fix works
=> Fixes GH actions deploy of codemirror playground

.changeset/nervous-taxis-admire.md, packages/language-support/src/syntaxColouring/syntaxColouring.ts, packages/language-support/src/syntaxColouring/syntaxColouringHelpers.ts, packages/language-support/src/tests/syntaxColouring/preparser.test.ts
To highlight the tokens we were:
1. Doing a first pass using the lexer
2. Fixing the highlighting with the parsing tree
The problem is we were storing the colouring in a map with key `line,column`, but we were not taking into account how many characters that highlighting affected. So for cases like:
```
CYPHER runtime = "some unfinished 
string
```
we would not colour the string correctly.
This PR adds the length of the colouring as a third coordinate in that map key, so we can solve those edge cases.
We were getting the highlighting of multiline constructs in the preparser incorrectly
=> Fixes bug with syntax highlighting of preparser options

packages/language-support/src/formatting/formattingHelpers.ts, packages/language-support/src/tests/formatting/formatting.test.ts, packages/react-codemirror/src/CypherEditor.tsx
I was reading through the [scalafmt thesis](https://geirsson.com/assets/olafur.geirsson-scalafmt-thesis.pdf) and came across section 4.2 which outlined some property based testing they used during development. They describe these as having "played a vital role in the development of scalafmt and gave us confidence that the [formatting algorithms] behave well against real world input". The three checks they relied on were
1. Can-format: If the scala compiler can parse the code, the formatter should be able to format it
2. AST-integrity: the AST should stay identical after formatting
3. Idempotency: Formatting twice should give the same output
Given that scalafmt is hugely successful, I figured we want to follow their advice. I already added nr 2 in a previous PR, but this PR introduces an …
=> Adds property checks to formatter

packages/language-support/src/formatting/formatting.ts, packages/language-support/src/tests/formatting/formatting.test.ts
We received a large (1.5M, though could only parse 1.1M) amount of real queries from our friends at #product-analytics, and I tried running the v1 formatter on these to verify it's behavior with the verifyFormatting funciton, i.e. that it 
1. Can format anything that the parser can parse
2. Does not produce a different parse tree after formatting
3. Is idempotent
After running the formatter over all of these queries I found that 
1. in some (veeery rare) cases, the "-" characters in relationships can be parsed as MINUS ( I have no clue how, since the arrowLine rule should catch these but whatever)
2. The formatter was completely missing path lengths in relationship patterns
3. The formatter was not putting spaces around IS in some cases, e.g. IS FLOAT was becoming ISFLOAT.
This PR fixes …
=> Fixes arrowlines, path length, and IS X bugs in formatter

.changeset/neat-panthers-whisper.md, packages/language-support/src/syntaxValidation/syntaxValidation.ts, packages/language-support/src/tests/syntaxValidation/syntacticValidation.test.ts
Before calls to built-in functions (example: randomUUID()) would get errors in language-support (but not when running query)
pre-fix: `RETURN randomUuid()` -> ~"Function randomUuid is not present in the database. Make sure you didn't misspell it or that it is available when you run this statement in your application"
now: `RETURN randomUuid()` -> no error
but still for non-built in:
`RETURN apoc.math.cosH(5)` -> "Function apoc.math.cosH is not present in the database. Make sure you didn't misspell it or that it is available when you run this statement in your application"
=> Fixes built-in function case sensitivity

packages/language-support/src/formatting/formatting.ts, packages/language-support/src/tests/formatting/formatting.test.ts
This PR fixes so that nested FOREACH clauses gets on a new line with indentation.
**Before**
```
FOREACH (i IN range(0, size(eventChain) - 2) |
FOREACH (node1 IN [eventChain[i]] |
FOREACH (node2 IN [eventChain[i + 1]] |
MERGE (node1)-[:NEXT_EVENT]->(node2))))
```
**After**
```
FOREACH (i IN range(0, size(eventChain) - 2) |
FOREACH (node1 IN [eventChain[i]] |
FOREACH (node2 IN [eventChain[i + 1]] |
MERGE (node1)-[:NEXT_EVENT]->(node2)
)
)
)
```
- One test added 
- All test passes
=> fixes so nested FOREACH gets newline and indent

packages/react-codemirror-playground/src/App.tsx
This PR updates react-codemirror-playground to check the system setting for darkmode. If darkmode is enabled on system, react-codemirror playground will default to darkmode. 
You might have talked about having this already and concluded you did not want to follow system settings, in that case remove this PR. 
- All tests passes
=> adds setting darkmode according to system pref

packages/language-support/src/formatting/formatting.ts, packages/language-support/src/tests/formatting/formatting.test.ts
While running our v2 formatter against real queries, we noticed some clauses in FOREACH statements were missing. The current visitForeachClause only visits the first clause though there may be multiple; hence them disappearing. 
This PR fixes the bug and adds a test for that case.
=> Fixes formatter bug; FOREACH with multiple clauses

packages/language-support/src/formatting/formattingv2.ts, packages/language-support/src/tests/formatting/formattingv2.test.ts
The PR which added the baseline of the V2 formatter had some known bugs which we decided to tackle later on, namely:
- Patterns and quantified patterns get weird spacing
- LIMIT does not get put on a newline (we forgot to port this to V2 I think)
- functions in listItemsPredicate are handled like keywords when they shouldn't be
- IN CONCURRENT... at the end of a subquery gets put on a new line for no reason.
This PR fixes these issues.
Relevant discussions in the previous PR:
-  https://github.com/neo4j/cypher-language-support/pull/369#discussion_r1967612286
-  https://github.com/neo4j/cypher-language-support/pull/369#discussion_r1967632302
- Unit tests added for all the cases above (roughly 8 tests)
- ran the sanity checks on 100k queries (no idempotency check because of the issues with …
=> Fixes known bugs in baseline PR for v2 formatter 

packages/language-support/src/index.ts, packages/react-codemirror-playground/src/App.tsx, packages/react-codemirror/src/CypherEditor.tsx
Given that we've now introduced the code for the experimental V2 formatter, we would like some convenient way to run it. This PR adds an option in the codemirror playground to enable switching between the versions by a checkbox in the options menu.
https://neo4j.slack.com/files/U05CXFC5V0U/F08F4STDWDQ/screen_recording_2025-02-26_at_10.03.27.mov?origin_team=T02AS3DQ7&origin_channel=C089SEWEJ8Z
- npm run test
- Tested manually as in the video above
=> Adds experimental formatting option to codemirror playground

packages/language-support/src/formatting/formattingSolutionSearchv2.ts, packages/language-support/src/formatting/formattingv2.ts, packages/language-support/src/tests/formatting/formattingv2.test.ts
We discussed the formatter briefly with Finbar Good, who provided us with some examples that were getting formatted incorrectly. These were mostly related to QPPs, as well as one case where a comment was getting hoisted to the previous line for no reason.
In short, the changes are
1. If either the start or end is missing from a QPP like this {start,end}, it gets replaced by a space. e.g. `{1,}` becomes `{1, }`
- It also turns out we were accidentally putting the end as the start before, i.e. `{,3}` was becoming  `{3,}`. This is also fixed with this PR
1. No space after a + or * QPP, e.g. `(a)-[]->+ (b)` becomes  `(a)-[]->+(b)` 
1. The determineSplits function will always return only a \n as an option if the nextChunk is a comment that was explicitly newlined, regardless of what the …
=> Fixes QPP behavior and a comment bug in V2 formatter

packages/language-support/src/formatting/formattingHelpersv2.ts, packages/language-support/src/formatting/formattingSolutionSearchv2.ts, packages/language-support/src/formatting/formattingv2.ts
This PR adds the functionality to tell the algorithm that between these chunks, you are never allowed to break. For example  `RETURN 1`, here it should be a avoidBreak() between the return and 1.
=> Adds avoid breaking

packages/vscode-extension/CHANGELOG.md, packages/vscode-extension/package.json
Adds `.cql, .cy, .cyp` as possible extensions for Cypher files in the VSCode plugin.
Closes #367
=> Adds .cy, .cyp and .cql extensions to the VSCode extension

packages/language-support/src/formatting/architecture.md, packages/language-support/src/formatting/architecture.png
In the architecture overview of the formatter, it was assumed that groups and indentation are chunks in the chunk list. Since we've recently changed this (courtesy of PR #375), this is now outdated. 
This PR updates the architecture diagram and removes the list item describing the old behavior.
Also, it makes the diagram twice as large, as some of the text got blurry in the smaller version
=> Updates architecture overview of formatter based on recent updates

packages/language-support/src/formatting/formattingSolutionSearchv2.ts, packages/language-support/src/tests/formatting/formattingv2.test.ts
As mentioned in the original V2 PR (#369), our caching of states is not perfect. One manifestation of this is the fact that function invocations with long namespaces rarely find their best solution. As an example, consider this query, which has been formatted with the current caching/memoization:
```
MATCH (userAccountInfo:UserAccountInformation)
WITH userAccountInfo, apoc.util.validate(NOT userAccountInfo.isVerified,
'Verification Error: The user account with unique identifier '
+
userAccountInfo.accountUniqueIdentifier
+ ' has not completed the mandatory ' +
'verification process required for accessing premium features. '
+
// The line below goes all the way to 142 (!!!)
'Please review your verification email and follow the provided instructions to secure your account.', …
```
=> Increases cache key granularity in formatter

packages/vscode-extension/src/connectionService.ts, packages/vscode-extension/src/webviews/connectionPanel.ts, packages/vscode-extension/src/webviews/controllers/connectionPanelController.ts
We got an issue from a user wanting to connect with ssc. This option adds that. For me, connecting with a ssc-supporting server with the new options worked, while connecting with a non-ssc server didnt, so looks good i suppose, but please do double check that it works for you :)
Closes #350
=> Adds neo4j+ssc and bolt+ssc as connection options

packages/language-support/src/formatting/formattingv2.ts, packages/language-support/src/tests/formatting/formattingv2.test.ts
As mentioned in #382, we currently have a bug where two of the 100k sample queries don't pass the idempotency check. It turns out that both of the cases were because we visit the wrong comma in cases where there can be multiple. Because comments are effectively "attached" to tokens, that caused them to disappear or get duplicated in some cases.
This PR fixes the issue in the returnItems and the callClause grammar constructs by keeping track of what comma we are at.
- All of the 100k sample queries now pass the integrity and idempotency checks.
- Added tests for both of the cases that weren't passing before
=> Fixes formatter missing/duplicating comments due to incorrect comma visit

packages/language-support/src/formatting/formattingv2.ts, packages/language-support/src/tests/formatting/commentsv2.test.ts, packages/language-support/src/tests/formatting/edgecasesv2.test.ts
In `addCommentsAfter`, we assume that groups can get attached to comment chunks, but this never seems to happen (and doesn't really make sense). Since comments do not get groups attached to them, alignment can break if they come right after the start of a clause. For instance, we would like the node pattern to align with the match here:
```
MATCH // Who comments here??
(m)--(n)
return n, m
```
but since the group gets attached to (m), and the comment forces a break, we get 
```
MATCH // Who comments here??
(m)--(n)
return n, m
```
This PR adds a utility function `startGroupAlsoOnComment` that works like startGroup() if the last token was not a comment, and otherwise attaches the group to the comment that came right after the previous non-comment token. Note that we can't take just the …
=> Fixes comments breaking clause alignment in formatter

packages/language-support/src/formatting/formattingv2.ts, packages/language-support/src/tests/formatting/edgecasesv2.test.ts, packages/language-support/src/tests/formatting/linebreaksv2.test.ts
Map projections, unlike map literals, currently do not get a wrapping group. This means that splits wihtin them look a bit weird:
```
MATCH (p:Person {name: "Alice"})
RETURN p {.name, .age, .email, .phone, .address, .occupation, .nationality,
.birthdate, .gender} AS personInfo
```
This PR adds a wrapping group within map projections, meaning they now get formatted like this:
```
MATCH (p:Person {name: "Alice"})
RETURN p {.name, .age, .email, .phone, .address, .occupation, .nationality,
.birthdate, .gender} AS personInfo
```
2 new tests added
- Note: One test fails right now due to an unrelated bug with function invocation alignment that will be resolved with #388
=> Fixes map projection alignment in formatter

packages/language-support/src/formatting/formattingv2.ts, packages/language-support/src/tests/formatting/linebreaksv2.test.ts
Since the formatter is allowed to break after `DISTINCT` on a `RETURN` clause, we can get this kind of weird formatting:
```
MATCH (abcde:wxyz)-[]->(fgh:wxyz)-[]->(ijk:wxyz)-[]->(lm:wxyz)
WHERE abcde.zxcvbnml = "XyZpQ8Rt"
RETURN DISTINCT
abcde.qwertyuiopa, abcde.zxcvbnmasdfgh, abcde.zxcvbnml, fgh.qwertyuiopa,
fgh.zxcvbnmasdfgh, fgh.zxcvbnml, ijk.qwertyuiopa, ijk.zxcvbnmasdfgh,
ijk.zxcvbnml, lm.qwertyuiopa, lm.zxcvbnmasdfgh, lm.zxcvbnml, lm.lkjhgfdswert
ORDER BY lm.lkjhgfdswert ASC
```
where the return items lose their alignment on the RETURN statement. This PR forces a non-break split after `DISTINCT`, meaning we now get 
```
MATCH (abcde:wxyz)-[]->(fgh:wxyz)-[]->(ijk:wxyz)-[]->(lm:wxyz)
WHERE abcde.zxcvbnml = "XyZpQ8Rt"
RETURN DISTINCT abcde.qwertyuiopa, abcde.zxcvbnmasdfgh, …
```
=> Fixes RETURN DISTINCT edgecase in formatter

packages/language-support/src/tests/formatting/edgecasesv2.test.ts
The CASE PR (#389 ) had a couple tests that actually produced a solution that was not optimal, but we decided to leave it since it had nothing with CASE statements to do, and was rather a fault of the memoizaiton / something else, and CASE statements were the last thing missing for V2. It appears the function alignment PR (#388) might have been the culprit, as it seems to have fixed the grouping issue which caused the tests fixed in this PR that weren't finding an optimal solution.
Regardless of the cause, the new solution that is being found is actually the intended one, and so this PR simply updates the test to match the output we are getting
=> Fixes formatting unit tests that now find optimal solution

packages/language-support/src/formatting/formatting.ts, packages/language-support/src/formatting/formattingHelpers.ts, packages/language-support/src/formatting/standardizer.ts, packages/language-support/src/tests/formatting/comments.test.ts, packages/language-support/src/tests/formatting/styleguide.test.ts
The [styleguide](https://neo4j.com/docs/cypher-manual/current/styleguide/) recommends that `ON CREATE` is put before `ON MATCH` in a `MERGE` clause if both are present. While this is a reasonable rule, **we do not think this falls under the responsibility of a formatter**. It is perhaps more appropriate for a linter. 
Since we blindly followed the styleguide while implementing the V1 formatter, we included this rule for good measure. This led to us having to create workarounds for the standardizing visitor, as it also shuffles the AST / CST, which would break the standardization if not accounted for. 
This PR removes the feature that shuffles the statements around, leaving them intact in the order that the user wrote them. It also removes the same feature/workaround from the standardizing …
=> Removes reordering of ON CREATE/MATCH clauses in formatter

packages/language-support/src/formatting/formatting.ts, packages/language-support/src/tests/formatting/edgecases.test.ts
While testing something else, I noticed that 2 of the 1.1M sample queries were not passing the AST integrity check, due to `IS CONNECTED` within relations being concatenated into `ISCONNECTED`. The issue was related to us always concatenating for path lengths even though a path length is not always present. This PR resolves that issue.
- Added a new test for this case
- Reran the 1.1m queries and now all of them pass both checks
=> Fixes IS CONNECTED concatenation bug in formatter

packages/language-support/src/formatting/formatting.ts, packages/language-support/src/formatting/formattingHelpers.ts, packages/language-support/src/formatting/formattingSolutionSearch.ts, packages/language-support/src/tests/formatting/linebreaks.test.ts, packages/language-support/src/tests/formatting/styleguide.test.ts
This PR improves the indentation of EXISTS expressions in Cypher queries. Similar to CALL expressions, the content inside EXISTS expressions should be properly indented, but when these expressions appear within WHERE clauses, the indentation requires special handling:
```
MATCH (user:Actor {actor_type: "EFXxFHob"})
WITH user,
apoc.coll.intersection(labels(user), idp_label_list) AS user_idp_labels
WHERE (size(user_idp_labels) = "3INQ6teR" OR user.service_type = "UlAAMmmD") AND
NOT EXISTS {
MATCH (user)-[:PART_OF]->(group:Actor {actor_type: "A0cFHwrB"})
WITH apoc.coll.intersection(labels(group), idp_label_list)
AS group_idp_labels
WHERE size(group_idp_labels) = "7SOM63mX" OR
group.service_type = "11gaOJfr" AND user_idp_labels = group_idp_labels
} AND toLower(user.status) = "p6MXYsvG"
RETURN …
```
=> Fixes EXISTS expressions

packages/language-support/src/formatting/formatting.ts, packages/language-support/src/tests/formatting/edgecases.test.ts
In #402 Oskar pointed out that one of his queries refused to format, and it turned out the formatter was experiencing an internal bug. The culprit turned out to be a QPP that failed because we always assume there is a comma within it, even though it can look like this as well: `{4}`
This PR addresses that grammar case in `visitQuantifier` and adds a test for it.
- Added a new test for the case described
- Tried the query mentioned in #402 and it now formats like expected.
- Ran about 50k sample queries for good measure to see if this breaks anything else and they passed
=> Fixes QPP with no comma bug in formatter

packages/language-support/src/formatting/formatting.ts, packages/language-support/src/formatting/formattingSolutionSearch.ts, packages/language-support/src/tests/formatting/linebreaks.test.ts
This PR fixes correct indentation for `COUNT` and `COLLECT`. This was something that was discovered in this PR: https://github.com/neo4j/cypher-language-support/pull/400
as something which should have similar behavior to `EXISTS`.
The following are before and after for `COUNT` and `COLLECT` respectively:
Before:
```
MATCH (person:Person)
RETURN person.name AS name, COUNT {
MATCH (person)-[:HAS_DOG]->(dog:Dog)
RETURN dog.name AS petName
UNION
MATCH (person)-[:HAS_CAT]->(cat:Cat)
RETURN cat.name AS petName } AS numPets
```
After:
```
MATCH (person:Person)
RETURN person.name AS name, COUNT {
MATCH (person)-[:HAS_DOG]->(dog:Dog)
RETURN dog.name AS petName
UNION
MATCH (person)-[:HAS_CAT]->(cat:Cat)
RETURN cat.name AS petName
} AS numPets
```
Before:
```
MATCH (person:Person)
RETURN person.name …
```
=> Fixes count and collect

packages/language-support/src/formatting/formatting.ts, packages/language-support/src/tests/formatting/linebreaks.test.ts
PR #382 added preservation of explicit newlines, but only between different clauses. As a result, in queries like:
```
MATCH (a)
RETURN a;
MATCH (b)
RETURN b;
```
the blank line  after `a;` is removed. This PR allows preserving newlines between statements, so that users can separate statements with a blank line.
4 new simple tests for statements with newlines after them
=> Adds preservation of newlines between statements in formatter

packages/language-support/src/formatting/formatting.ts, packages/language-support/src/tests/formatting/linebreaks.test.ts
Greg noted that some of the examples from [this page](https://neo4j.com/docs/cypher-manual/current/patterns/shortest-paths/) have some quirks that would be good to straighten out. This PR addresses those concerns, by making the following changes:
- The selector (e.g. `SHORTEST 1`) now prefers not to split (and if it does, it lines up to the right of the path if there is one)
- Fixed a grouping issue with listItemsPredicate
- I considered forcing a break after the WHERE as well but that only made it worse in my opinion
- Parenthesized paths with a quantifier prefer to stick together.
- I considered a forced break after quantifiers, which looks good in some examples, but looks weird for e.g. this one MATCH (p)-[]->*(q)
```
MATCH SHORTEST 1 (:Station {name: 'Hartlebury'}) (()--(n))+ …
```
=> Improves formatting of shortest path examples

packages/language-support/src/formatting/formatting.ts, packages/language-support/src/tests/formatting/edgecases.test.ts
We got some feedback in the #team-cypher thread about certain weird functions getting formatted like keywords. #407 fixed one of these issues, but there were 4 cases in total that behaved similarly. We already handle three of them, but `normalizeFunction` is still broken similarly to trim(). This PR fixes that (final) case as well.
They also mentioned that "_we will be adding VECTOR for the vectorValueConstructor soonish too_" which we might want to look out for in the future.
Adds tests for normalize which cover all the ways it can be expressed according to the grammar
=> Fixes formatter treating normalize as a keyword

packages/language-support/src/formatting/formatting.ts, packages/language-support/src/formatting/formattingHelpers.ts, packages/language-support/src/formatting/formattingSolutionSearch.ts
This PR primarily addresses technical debt related to how indentation is handled. Additionally, it removes some unnecessary checks, improving code clarity.
In PR: https://github.com/neo4j/cypher-language-support/pull/404 and https://github.com/neo4j/cypher-language-support/pull/400 a changes was made to how indentations was made. However, these also introduced tech debt in form that it became much more difficult to understand how indentation works. This is hopefully improved in this PR. The main idea is to create a clear distinction between how indentation is handled in the Chunk, and how the chunk affects the State:s indentation.
The function which calculates the indentation for the current chunk also got an overhaul. Instead of nested if statements we do a if check and return …
=> Fixes tech debt (indentations, outdated code) for formatter

packages/vscode-extension/package.json
Configuring the formatter keyword is so that when someone tries to format a cypher file they get suggested our extension:
Adding `"editor.defaultFormatter": "neo4j-extensions.neo4j-for-vscode"` I'm hoping people don't get the following in Cypher files:
=> Configures defaults for formatting VSCode package.json

packages/vscode-extension/src/connectionService.ts, packages/vscode-extension/tests/specs/unit/executeCommands.spec.ts
I've noticed that most of the e2e CI / CD runs have been failling recently, see for instance;
https://github.com/neo4j/cypher-language-support/actions/runs/13897318639/job/38880796738?pr=412
https://github.com/neo4j/cypher-language-support/actions/runs/13897573797/job/38881589386?pr=411
They all fail due to the the test `Deleting another connection should not disconnect the current one` which makes sure that deleting a connection that is not the activec one does not give a "disconnected" message (as far as I can tell, at least).  
This was actually brought up by @anderson4j while reviewing this PR https://github.com/neo4j/cypher-language-support/pull/357 and a test was added for it, but for some reason the functionality works locally but not on the GH e2e test runner 😢 
This PR adds the …
=> Fixes connection state incorrectly being set to inactive

packages/language-support/src/formatting/formatting.ts, packages/language-support/src/tests/formatting/commands.test.ts
Commands are administrative queries that you can run against a neo4j database, such as 
```
CREATE CONSTRAINT `constraintName` IF NOT EXISTS
FOR (n: nodeType)
REQUIRE (n.id) IS UNIQUE;
```
or a plethora of other ones, such as `DROP INDEX`, `SHOW TRANSACTIONS` etc. etc.
As of yet, we have had very limited support for these, beyond capitalizing the keywords. The main reason for this is that commands have grammar that is essentially completely separated from the rest of the grammar (including e.g. node and relationship patterns). This PR adds support for _most_ of the common commands.
Most queries are not commands. In fact, out of 1174529 queries, 11749 of them (1%) were commands or contained at least one command. Further, out of those 11749 commands, 7811 of them contained "CREATE …
=> Adds support for common commands to formatter

.github/workflows/fetch-dev-artifacts.yaml
Before accessing secrets like ${{ secrets.AWS_ACCESS_USERNAME }} would access AWS_ACCESS_USERNAME from the repo secrets. Now with the secrets moved to a repo environment (aws-codeartifacts) this PR allows us to access them from there
=> Adds an environment to AWS-codeartifact fetching workflow

package-lock.json, packages/vscode-extension/package.json, packages/vscode-extension/src/commandHandlers/connection.ts, packages/vscode-extension/src/commandHandlers/params.ts, packages/vscode-extension/src/constants.ts, packages/vscode-extension/src/parameterService.ts, packages/vscode-extension/src/registrationService.ts, packages/vscode-extension/tests/specs/webviews/params.spec.ts
This PR introduces a couple of improvements to the parameters pane:
* Adds icons to edit / remove a parameter when you get on top of it in the VSCode parameter pane.
Unfortunately those icons cannot be permanently shown, you need to hover on the params pane.
* ~Aside from that, I realized we could not set parameters if we were connected to the system database and we were getting a very cryptic message. I've just added an extra step to find a `user` database from the ones in the active connection, so we evaluate the parameters against that database.~ Gives a better error message when trying to evaluate params against the system database.
=> Adds icons to edit/delete params, better error message when setting against system

.github/workflows/fetch-dev-artifacts.yaml, packages/vscode-extension/tests/specs/api/autoCompletion.spec.ts
Bear in mind the database is cut off 
This PR contains changes to:
* Fix the cron job expression we were using, which was executing everyday from the 1st day on the month to the 7th and on Fridays. We wanted something that was executing only the first Friday of every month, but that does not seem possible to get with cron, so we have settled for executing the 4th day of the month and the 7th day of the month. 
In the worst case scenario the 1st day of the month is a Friday so we would get the update on the Sunday (3rd day), leaving us with a whole week to do the changes. If the 1st day of the month was a Saturday, then we would get this update on the first Friday, the 6th.
* Uses a PAT token to make the PRs execute the CI when they are opened, rather than the default `GITHUB_TOKEN`
=> Adjusts job to update grammar and semantic analysis

packages/vscode-extension/README.md, packages/vscode-extension/package.json, packages/vscode-extension/resources/images/demo-add-parameter.png, packages/vscode-extension/resources/images/demo-connect.png, packages/vscode-extension/resources/images/demo-disconnect.png, packages/vscode-extension/resources/images/demo-embedded-cypher-menus.png, packages/vscode-extension/resources/images/demo-execution.png, packages/vscode-extension/resources/images/demo-manage-connection.png, packages/vscode-extension/resources/images/demo-new-connection.png, packages/vscode-extension/resources/images/demo-param-editing.png
* Gets out of the preview mode (no more red preview banner on the VSCode marketplace)
* Reviews the VSCode extension `README`
* Corrects a few small bugs in the VSCode extension `package.json` (we could not use the embedded menus to create a cypher file from a selection in Java for example) or we were showing `Neo4j: Neo4j Run Cypher statements` in the command palette (duplicated `Neo4j`)
=> Prepares VSCode release

.github/workflows/fetch-dev-artifacts.yaml
This way the workflow will be scheduled to run on all fridays, but checking if it's the first friday of the month before running any fetching
=> Modifies fetch-dev-artifacts to only fetch on the first friday

.changeset/chatty-needles-guess.md, package-lock.json, packages/language-support/src/antlr-grammar/CypherCmdLexer.g4, packages/language-support/src/antlr-grammar/CypherCmdParser.g4, packages/language-support/src/lexerSymbols.ts, packages/language-support/src/parserWrapper.ts, packages/language-support/src/tests/consoleCommands.test.ts
This pr is to add support for the `:play` command, which is used to play custom guides within the query application.
=> adding support for :play command

packages/language-support/src/formatting/formatting.ts, packages/language-support/src/formatting/formattingSolutionSearch.ts
There are a few queries that result in groups being started but never ended, or vice versa. This should never happen if all visit methods are correct, though because of some complicated cases (pun intended) it still happens.
This PR fixes all of those cases, and additionally adds adds two checks:
1. We should never end a group if there is not a group active
2. There should not be any active groups left when we are done formatting
If either of these are true, **the formatter suffers an internal error**.
- No new tests added, but all tests pass without triggering the above checks.
=> Adds check to formatter that ensures correct group starts/ends

.changeset/rich-fans-happen.md, package-lock.json, packages/language-support/src/parserWrapper.ts, packages/language-support/src/syntaxValidation/syntaxValidation.ts, packages/language-support/src/tests/syntaxValidation/semanticValidation.test.ts, packages/language-support/src/tests/syntaxValidation/syntacticValidation.test.ts
This pr is to show semantic errors to users for the missing parameters. 
A look from my local:
=> adding semantic validation for missing paramters

packages/vscode-extension/package.json
It shouldn't be there, it will fail from the palette because it requires the database item as an input.
=> Removes switch database command from the palette

.github/actions/setup-and-build/action.yaml, .github/workflows/archive-vscode-artifacts.yaml, .github/workflows/benchmark.yaml, .github/workflows/ci.yaml, .github/workflows/deploy-demo.yml, .github/workflows/formatting-integrity-check.yaml, .github/workflows/publish-npm-packages.yaml, .github/workflows/publish-vscode-extension.yaml, packages/language-support/src/index.ts, packages/react-codemirror/package.json, packages/react-codemirror/playwright-ct.config.ts, packages/vscode-extension/package.json, packages/vscode-extension/src/commandHandlers/connection.ts, packages/vscode-extension/src/commandHandlers/params.ts, packages/vscode-extension/tests/specs/api/autoCompletion.spec.ts, packages/vscode-extension/tests/specs/webviews/params.spec.ts, packages/vscode-extension/tests/webviewUtils.ts
Based on #461
- Splits e2e jobs to run in parallel
- Adds cache on commit to avoid rebuilding
- Cancel old jobs on the same pull request
- Fixes parameter can't be set on system flaky test by improving the UX. We not instantly give the error (same as when disconnected), instead of letting the user fill in all the values and then giving an error ✨ 
On flakyness:
- [Ideally each test should be as isolated as possible](https://playwright.dev/docs/best-practices#make-tests-as-isolated-as-possible). This is so they can run / re-run in parallel, etc. This means they need to ensure their own connection etc in a `beforeEach`. I'm not sure if this applies to the vscode tests though as it's not got multiple browser windows like playwright tests do 🤔
=> Improve CI speed

.github/workflows/publish-vscode-extension.yaml
* We fixed the `vsce` command for packaging, but not for publishing.
* The command `ovsx` has the same problem than the `vsce` one (it doesn't support pnpm). In this issue https://github.com/eclipse/openvsx/issues/368 they suggest passing the `--yarn` flag to it, but that doesn't seem very trustworthy, I've used the same `--no-dependencies` flag than for `vsce`.
=> Fixes the VSCode CI job, second attempt

.github/workflows/publish-npm-packages.yaml
For some reason when we go through the changeset action we cannot publish npm packages (whereas the canary releases job is working fine):
@OskarDamkjaer found this that might fix it: https://github.com/changesets/action/issues/98#issuecomment-2519457411
where they suggest adding the `NODE_AUTH_TOKEN` to the job, which makes sense because that's the only difference in setup I could find with respect to the canary releases job (although that one doesn't use the changeset action)
=> Fixes npm publishing

packages/language-support/src/formatting/formatting.ts, packages/language-support/src/tests/formatting/linebreaks.test.ts
For some reason, the formatter allows a break between `CALL` and `{` in `subqueryClause`s, which leads to this kind of ugly output:
```
MATCH
u0 =
(v3:mn:op:tuv {xy: fghij})-[s1:abc {m1: "x"}]->
(w2 {n5: [-8392754106, 517362948, 2073946581]})
WITH
u0,
COLLECT {
MATCH x1 = (y0)
CALL
{
WITH w2, s1, u0
MATCH
c2 =
(w2)<-[t2:defg]-
(:wx:tuv:mn:yz:op:ab:cd:ef:gh)--
(z1)-[:hij*..8]->
(:mn:ij:ab {m1: "y"})--
(w2)-[:klm {pqr: 714026583}]->
(a5:ij {xy: fghij})
CALL
{
WITH w2, t2, u0, c2
OPTIONAL MATCH (:wx)
RETURN w2 AS b6
}
RETURN s1 AS e5, c2 AS d3
}
RETURN e5.stu
} AS uvwxyz
RETURN *
```
So there's simply a `avoidBreakBetween` call missing, which this PR adds. Credit to Joel from the Cypher team for noticing this and providing an example (the one above, I've anonymized it).
Also, while looking …
=> Fixes CALL papercuts in formatter

.github/workflows/fetch-dev-artifacts.yaml
Looks like there was a mistake in the action folder name when adding the "build project" step.
This changes it so the step points to the intended action. Tried it in my private copy of the repo and the build step passes now.
=> Fixes build step in fetch-dev-artifacts

.github/workflows/fetch-dev-artifacts.yaml
Old way to get date got them with zero padded format, which broke the day-of-month test for single-digit days, so the test would incorrectly run on fridays that are the 8th or 9th. 
Fix is to add a "-" after the % specifying what part of date you want (see [](https://linux.die.net/man/1/date))
Tried the workflow on my private copy of the repo with this fix and got 9 instead of 09 on the 9th.
=> Removes zero-padding of day

package.json, packages/language-support/src/tests/formatting/verification/verificationCheck.ts, pnpm-lock.yaml
This PR #495  switched the repo to ESM, by adding `"type":  "module"` in `package.json`. Unfortunately, **ts-node** doesn’t fully support ESM resolution, so our integrity-check script started failing whenever it tried to import other files.
- **Replace `ts-node` with `tsx`** for the integrity-check script, since `tsx` has ESM support.  
- In ESM mode, `__dirname` is undefined. Our tests relied on `__dirname` to locate the JSON query files.  
- I instead used `import.meta.url`, but VS Code flags that in the editor because our `tsconfig.json` still specifies `"module": "commonjs"`.  
- Since this script is run directly via `tsx` (and never compiled with `tsc`), I choose to ignore the red squiggles in the editor with ts-ignore comment
A possible solution instead of the `ts-ignore` comment …
=> Fixes formatter integrity check test

packages/language-support/src/formatting/formatting.ts, packages/language-support/src/tests/formatting/commands.test.ts, packages/language-support/src/tests/formatting/edgecases.test.ts
This PR improves some of the nice list/map printing introduces in #478. I first noticed that OPTION did not have `oneChunkPropery` which means it could not get the nice map formatting (found out by the fourth example in codemirror). Then another test failed in which I noticed that key maps also should have the property to have lists which formats nicely. 
All in all, this PR improve from this:
```
OPTIONS
{
aaaaaa: "20z9vakp",
aaaaaa:
{
aaaaaa: ["aotV0uiw", "SCxu0Vyn", "ekTx6ngu"],
aaaaaa: ["WqAr9IvS", "j5fYJwuN"],
aaaaaa: ["HUDXLCRN", "LUfKWGc7"],
aaaaaa: ["qbk3JzMe", "Ca4n1Ea9", "I96Uwq16"],
aaaaaa: ["zcBcWjoJ", "dz78begI"],
aaaaaa: ["MIADLwls", "qkacQgzY", "wYYAgiGo"],
aaaaaa: ["Jmw0tXjZ", "ALiXrHno", "QRYTGYFd"],
aaaaaa: ["EEJJKZGC", "GGDt2msc"]
}
}
```
To this:
```
OPTIONS {
aaaaaa: …
```
=> Improves map formatting

packages/vscode-extension/src/extension.ts, packages/vscode-extension/src/linterSwitching.ts
In my recent PR I moved so we create the extension folder on startup. This breaks the old linter handling if we remove the folder they are stored in after startup, as in the new e2e test.
This alters all accesses of the globalstorage uri to go through a method that recreates the folder if it is missing
=> Fixes extension folder being removed from breaking linter switching

.changeset/wild-rooms-shop.md, packages/query-tools/src/neo4jConnection.ts, packages/vscode-extension/src/webviews/queryResults/queryDetailsProvider.ts
Certain queries, like those with "call in transactions" need to be run in implicit transactions, which we previously didnt support. In upx, this was solved by re-running queries with specific errors in an implicit transaction, so to keep the code understandable I do the same in this PR.
Before: 
Now:
=> Re-run queries that need implicit transaction

packages/vscode-extension/tests/runWebviewTests.ts
Some overnight update (think the update to vscode yesterday https://code.visualstudio.com/updates/v1_103) caused the webview tests to start failing. It looks like the chromedriver fetched by wdio-vscode-service started requiring a newer chrome version than the one we had
error:
```
[0-0] session not created: This version of ChromeDriver only supports Chrome version 138
[0-0] Current browser version is 124.0.6367.243 ...
```
Updating the vscode version used in the tests brought in the newer browser and fixed this bug, but updating to latest brought in some new issues for the tests themselves. Visually I saw that the latest version had copilot introduced by default, so maybe this is causing some issues with the available views... 
Either way, I think we should merge in this working config …
=> Bugfix webview tests 

.github/workflows/pre-release-vscode-extension.yaml
This pr is to use the browser bot instead of the github action's bot to allow it to push to the main branch.
=> changing to use browser bot instead of the action bot

.changeset/slick-pandas-dance.md, packages/language-support/src/parserWrapper.ts, packages/language-support/src/tests/syntaxValidation/syntacticValidation.test.ts
We have logic that looks through the parse-tree for labels/rels used in the query, and then warns if these are not available on the db. Certain queries would not get these warnings though - see image below
The issue arose because of a check to prevent another bug. We were getting these "missing label"-warnings when the parser recovered by deleting tokens. This would give warnings like ~"RETURN is not a label in the db" on `MATCH (n:) RETURN`. 
The new logic handles the parser recovery too (see test syntacticValidation.test.ts -> `Syntax validation errors on missing label expression` which is still passing), but without covering the above mentioned legitimate warnings, resulting in the expected:
=> Fix missing label warnings

.changeset/thick-signs-prove.md, packages/language-support/src/formatting/formattingHelpers.ts, packages/language-support/src/tests/formatting/edgecases.test.ts
Fixes the issue mentioned in: https://github.com/neo4j/cypher-language-support/issues/551
Basically, when keywords that would be capitalized in the preparser are used in functions/procedures, these were also capitalized in functions/procedures that used them, which actually breaks case-sensitive cases.
When checking whether we should capitalize a keyword we already had the check for isSymbolicName, but it didn't cover the full rule containing preparserKeywords. It also didnt cover the case when the rule was higher up in the parent chain, which was the case here, see image below, so all that was needed was to adjust the check a little bit.
The image is from looking at the parser node that we check for capitlizing (or not) the namespace `cypher` in the procedure call of the query used here: …
=> Fixes formatter capitalizing preparser keywords in procedure/function namespaces

.github/workflows/fetch-dev-artifacts.yaml
We recently moved the browser-bot PAT from being an env secret to instead be a repo-wide secret, since we use it in two different environments right now (this, and the prerelease workflow - and could very well want it in another later). To be sure it worked, we checked that the pre-release workflow worked, and since it does, we should safely be able to use the PAT here too
=> use repo-wide PAT for fetch-dev-artifacts
