packages/language-server/README.md, packages/language-support/README.md, packages/react-codemirror/README.md, packages/react-codemirror/src/CypherEditor.tsx
Also adds some js doc comments to make importing using the react editor a bit smoother
=> Adds usage examples to README.md

.changeset/nervous-rabbits-greet.md, .changeset/pre.json, packages/language-server/CHANGELOG.md, packages/language-server/README.md, packages/language-server/package.json, packages/vscode-extension/CHANGELOG.md, packages/vscode-extension/package.json, packages/vscode-extension/src/extension.ts
So it can be used with:
```
npm i -g @neo4j-cypher/language-server
cypher-language-server --stdio
```
=> Makes language server executable

.changeset/violet-peas-float.md, packages/language-support/src/highlighting/syntaxValidation/semanticAnalysisWrapper.ts, packages/language-support/tsconfig.json
This makes semantic analysis x2 faster, sometimes even x4 times:
Some examples. Before:
```
Semantic validation spec
✓ Shows errors for undefined variables (238 ms)
✓ Accumulates several semantic errors (104 ms)
✓ Shows errors for CALL IN TXs used in UNION (83 ms)
✓ Shows errors for CALL when return variable already bound (86 ms)
✓ Shows errors for subquery with only WITH (64 ms)
✓ Does not show errors for multiple USE with the same database (107 ms)
✓ Shows errors for using multiple USE with different databases (74 ms)
✓ Shows errors for simple shadowing of variables (99 ms)
```
After:
```
Semantic validation spec
✓ Shows errors for undefined variables (137 ms)
✓ Accumulates several semantic errors (62 ms)
✓ Shows errors for CALL IN TXs used in UNION (34 ms)
✓ Shows errors for CALL when …
```
=> Makes semantic analysis faster

packages/language-support/src/highlighting/syntaxValidation/semanticAnalysisWrapper.ts, packages/language-support/src/highlighting/syntaxValidation/syntaxValidation.ts, packages/language-support/src/parserWrapper.ts, packages/language-support/src/tests/highlighting/syntaxValidation/semanticValidation.test.ts
* Adds notifications to the semantic analysis. All of the notifications will be surfaced as warnings.
* Provides a better surface to access the semantic analysis.
=> Adds notifications to the semantic analysis

.github/workflows/benchmark.yaml
Because the push to Grafana step is failing for main
=> Fixes pushing to Grafana

packages/language-server/src/autocompletion.ts, packages/language-support/src/autocompletion/autocompletion.ts, packages/language-support/src/helpers.ts, packages/language-support/src/parserWrapper.ts, packages/language-support/src/signatureHelp.ts, packages/language-support/src/tests/autocompletion/completionAssertionHelpers.ts, packages/language-support/src/tests/benchmarks/benchmark.ts
Because we want to avoid reparsing when possible
=> Adds caret to auto-completions

docs/semantic-analysis.md, packages/language-support/src/tests/syntaxValidation/semanticValidation.test.ts
This includes the transpiled files from neo4j to include the procedure registry in the javascript. It is almost a no-op, only bringing some changes to other errors that are surfaced.
=> Updates transpiled semantic analysis to have the procedure registry

.changeset/pre.json, package-lock.json, packages/vscode-extension/package.json, turbo.json
`neo4j-vscode` was taken sadly 😢
=> Polishes last bits for publishing the extension

.eslintignore, packages/language-support/src/tests/testData.ts, packages/react-codemirror/src/e2e_tests/signatureHelp.spec.tsx, packages/react-codemirror/src/lang-cypher/createCypherTheme.ts, packages/react-codemirror/src/lang-cypher/signatureHelp.ts, tsconfig.node.json, turbowatch.ts
Here's how it looks:
https://github.com/neo4j/cypher-language-support/assets/10564538/63660615-4d13-4584-9db4-215def412fce
Want to have greg & you try it and give feedback for the next steps.
I also added a ts-config for the turbowatch file, so we don't need to ignore it from the styling linting anymore.
=> Signature Help CSS, step in the right direction

package-lock.json, packages/vscode-extension/package.json
Before:
```
230 packages are looking for funding
run `npm fund` for details
3 vulnerabilities (2 moderate, 1 high)
To address all issues, run:
npm audit fix
Run `npm audit` for details.
```
=> Updates packages to remove security vulnerabilities

.github/workflows/archive-vscode-artifacts.yaml, .github/workflows/publish-vscode-extension.yaml
Archives VSCode artifacts when merging to `main`. The result can be seen in [0b79209](https://github.com/neo4j/cypher-language-support/pull/257/commits/0b79209cd60f4d5b1ab87734a5b779f9bf9a31fa)
=> Archives VSCode artifacts

.changeset/fuzzy-rice-train.md, .changeset/nervous-rabbits-greet.md, .changeset/pink-chefs-trade.md, .changeset/pre.json, .github/workflows/publish-npm-packages.yaml, package-lock.json, package.json, packages/react-codemirror-playground/CHANGELOG.md, packages/react-codemirror-playground/package.json, packages/react-codemirror/CHANGELOG.md, packages/react-codemirror/package.json, packages/vscode-extension/CHANGELOG.md
It was failing with a cryptic message:
```
🦋  error TypeError: Cannot destructure property 'packageJson' of 'undefined' as it is undefined.
🦋  error     at Object.shouldSkipPackage (/home/runner/work/cypher-language-support/cypher-language-support/node_modules/@changesets/should-skip-package/dist/changesets-should-skip-package.cjs.js:6:3)
🦋  error     at getRelevantChangesets (/home/runner/work/cypher-language-support/cypher-language-support/node_modules/@changesets/assemble-release-plan/dist/changesets-assemble-release-plan.cjs.js:560:[29](https://github.com/neo4j/cypher-language-support/actions/runs/10666433652/job/29561851700#step:6:30))
🦋  error     at Object.assembleReleasePlan [as default] (/home/runner/work/cypher-language-support/cypher-language-support/node_modules/@changesets/ass …
```
=> Fixes changeset action

.eslintignore, docs/semantic-analysis.md, modify-semantic-analysis.js
This gets us closer to having automatic PRs to update those artifacts.
=> Adds script to programatically modify the semanticAnalysis.js file

package-lock.json, packages/vscode-extension/CHANGELOG.md, packages/vscode-extension/package.json, packages/vscode-extension/src/commandHandlers.ts, packages/vscode-extension/src/constants.ts, packages/vscode-extension/src/cypherRunner.ts, packages/vscode-extension/src/registrationService.ts, packages/vscode-extension/tests/fixtures/multiline.cypher, packages/vscode-extension/tests/runWebviewTests.ts, packages/vscode-extension/tests/specs/unit/cypherRunner.spec.ts, packages/vscode-extension/tests/specs/webviews/queryExecution.spec.ts, packages/vscode-extension/tests/specs/webviews/setup.spec.ts, packages/vscode-extension/tests/webviewUtils.ts
If we select some specific text in VSCode, we want to run only that part of the query.
One thing I don't quite like is that the order in which the statements would be executed depends on what order you highlight them. Should we maintain that?
=> Adds feature to run selection in VSCode

.changeset/cyan-seals-burn.md
There are no changes to the grammar files
=> Updates semantic analysis and grammar for version 2025.01.0

CONTRIBUTING.md
Hey,
I tried building the project and got stuck on
1. Java being a requirement but not being listed
2. Incorrect npm run command (`dev-codemirror`, not `dev:codemirror`)
First time contributing so let me know if I'm not following your  conventions correctly :)!
=> Updates readme with minor things I got stuck on

packages/react-codemirror/src/CypherEditor.tsx
This PR should fix the issue when the react-codemirror is imported with extrak keybindings
=> Fixed keybind issue when importing this component with extra keybinding

.changeset/itchy-deers-type.md, packages/language-support/src/antlr-grammar/Cypher25Lexer.g4, packages/language-support/src/antlr-grammar/Cypher25Parser.g4, packages/language-support/src/lexerSymbols.ts
Updates semantic analysis and parser artifacts
=> Update parser and semantic analysis to 2025.02

packages/language-support/src/autocompletion/completionCoreCompletions.ts, packages/language-support/src/tests/autocompletion/miscCompletions.test.ts
We want to get the `CYPHER 25` completion if the corresponding feature flag is enabled
=> Completes CYPHER 25 if the feature flag is enabled

packages/vscode-extension/src/webviews/connectionPanel.ts, packages/vscode-extension/tests/specs/webviews/connection.spec.ts, packages/vscode-extension/tests/specs/webviews/setup.spec.ts, packages/vscode-extension/tests/webviewUtils.ts
This solves a bug when opening a connection form, which would lose the details when switching to another tab.
https://github.com/user-attachments/assets/20d247ca-37a8-4155-89a5-21f65393e764
=> Solves issue when filling in data in connection tab

packages/language-support/src/formatting/formattingHelpersv2.ts, packages/language-support/src/formatting/formattingv2.ts, packages/language-support/src/tests/formatting/formattingv2.test.ts
This PR fixes small bugs which has been on TODO. 
The tests 'should not level dangling bracket' and 'should align with list predicate' are related to the fixes in the code. While test q22 and q23 has been failing before because of exceeding width limit of 80 characters. But this [PR](https://github.com/neo4j/cypher-language-support/pull/375) fixed that.
=> Fixes small bugs for formatter

packages/vscode-extension/package.json, packages/vscode-extension/src/commandHandlers/params.ts, packages/vscode-extension/src/constants.ts, packages/vscode-extension/src/parameterService.ts, packages/vscode-extension/src/registrationService.ts, packages/vscode-extension/src/treeviews/parametersTreeDataProvider.ts, packages/vscode-extension/tests/specs/webviews/params.spec.ts
This adds both a command and a context menu right click option to delete parameters individually.
=> Adds parameter deletion ability in VSCode

packages/vscode-extension/package.json
When hovering over a connection, you will now see icons that allow you to edit/delete it.
https://github.com/user-attachments/assets/2a4093dc-966c-4723-988d-476719efc324
=> Adds icons for editing/deleting connections

packages/react-codemirror/src/index.ts, packages/vscode-extension/src/commandHandlers/params.ts
Uses a timeout to prevent parameter validation from running until the user has not changed input for 200 ms.
Previously every keystroke would cause validation to run and change the validation message, but now if you type quite quickly it will wait for a stop in typing.
=> Adds debouncing to parameter validation

packages/language-support/src/index.ts
I missed the default exports noah needed, that i bundled in the #480 change
=> Fix missing default exports in Language Support

package.json
Now cleans tsconfig.tsbuildinfo files too, fixes build failing even after deep-clean
=> Expands deep-clean command

packages/vscode-extension/README.md
=> Remove "preview" from vscode readme

packages/vscode-extension/src/commandHandlers/linters.ts, packages/vscode-extension/src/constants.ts, packages/vscode-extension/src/linterService.ts, packages/vscode-extension/src/linterSwitching.ts, packages/vscode-extension/src/registrationService.ts, packages/vscode-extension/tests/mocks/mockExtensionContext.ts, packages/vscode-extension/tests/specs/api/lintSwitching.spec.ts, packages/vscode-extension/tests/specs/unit/executeCommands.spec.ts
Because the e2e tests go through the dynamic adjusting flow but we didn't have tests for checking the manual adjusting
=> Adds more tests for the linter switching feature
